# CircleCI configuration file
version: 2
jobs:
  build:
    docker:
      - image: chmodas/docker-scala-sbt:11

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      # Create a separate environment for each build for security.
      # A step required to run docker and docker-compose commands.
      - setup_remote_docker:
          version: 19.03.13

      # Start the Docker containers
      - run: docker-compose -p akka-persistence -f docker/docker-compose.yml up -d

      # Build and test with 2.12.x
      # - run: sbt ++2.12.13 test

      # Build and test with 2.13.x
      # - run: sbt ++2.13.4 test

      # Stop the Docker containers
      - run: docker-compose -p akka-persistence -f docker/docker-compose.yml down
