version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_DB: db
    volumes:
      - ./postgres-schema.sql:/docker-entrypoint-initdb.d/1000_postgres-schema.sql
    ports:
      - 5432:5432
    networks:
      - akka-persistence-r2dbc
    command: ["postgres", "-c", "log_statement=all"]

networks:
  akka-persistence-r2dbc:
