name: akka-persistence-r2dbc CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the build container
        uses: docker://chmodas/docker-scala-sbt:11
      - name: Checkout the code
        uses: actions/checkout@v1
      - name: Start the Docker containers
        run: sbt dockerComposeUp
      - name: Build and test with 2.12.x
        run: sbt ++2.12.12 test
      - name: Build and test with 2.13.x
        run: sbt ++2.13.3 test
      - name: Stop the Docker containers
        run: sbt dockerComposeStop
      - name: Publish
        if: ${{ github.event_name != 'pull_request' && github.event_name != 'schedule' }}
        run: sbt -Dbintray.user=${{secrets.BINTRAY_USER}} -Dbintray.pass=${{secrets.BINTRAY_PASS}} publish

